import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/provider/AuthProvider";
import ContextProvider from "@/provider/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Journal X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <ContextProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
